### ISSUE TITLE
Firefox Port?

### ISSUE THREAD

**Issue by YKoas** [djm30/Distraction-Free-Reddit#1]
Hi! Cool idea and was wondering if there's a chance of a firefox port/add-on version?

**Comment by djm30** [comment]
I'll definitely have a look into porting it to Firefox in the next few months

**Comment by YKoas** [comment]
That'll be fantastic! Maybe coordinate with Minimal as they seem to share some aims? https://gitlab.com/aupya/minimal

**Comment by djm30** [comment]
Just got the firefox version published, you can find it at https://addons.mozilla.org/en-GB/firefox/addon/distraction-free-reddit. If you have any issues with it please let me know!

**Comment by YKoas** [comment]
Thanks! Unfortunately though it's not working for me/making any changes?

**Comment by djm30** [comment]
If you click on the extension button in firefox, then click on manage extensions, click on Distraction Free Reddit and then go to permissions, check _Access your data for sites in the *://reddit.com domain_ is enabled. I'm not too sure why this is an optional permission so will work on getting that fixed but that should get it up and running hopefully.

**Comment by djm30** [comment]
I think I have fixed the permissions now with Firefox, if you remove and reinstall the latest version, it should ask you for all the permissions it needs on installation now and work straight away.
